// Code generated by flatc command **DO NOT MODIFIED THIS CODE**

public enum AnySwift: UInt8 {
	case NONE = 0
	case Monster = 1
	case TestSimpleTableWithEnum = 2
	case MyGame_Example2_Monster = 3
}

